# Generated by Django 6.0.6 on 2026-06-17 16:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('length', models.IntegerField(verbose_name='Длина пароля')),
                ('use_uppercase', models.BooleanField(default=True, verbose_name='Заглавные буквы')),
                ('use_lowercase', models.BooleanField(default=True, verbose_name='Строчные буквы')),
                ('use_digits', models.BooleanField(default=True, verbose_name='Цифры')),
                ('use_symbols', models.BooleanField(default=False, verbose_name='Спецсимволы')),
                ('exclude_ambiguous', models.BooleanField(default=False, verbose_name='Исключить неоднозначные')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'История пароля',
                'verbose_name_plural': 'История паролей',
                'ordering': ['-created_at'],
            },
        ),
    ]
